FROM arm32v7/node:stretch

ADD . /app
WORKDIR /app
RUN npm install

RUN useradd -d /home/term -m -s /bin/bash term
RUN echo 'term:term' | chpasswd

EXPOSE 3000

ENTRYPOINT ["node"]
CMD ["app.js", "-p", "3000"]
